# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'v3.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(821, 611)
        MainWindow.setFixedSize(821,611)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.find_dir_button = QtWidgets.QToolButton(self.centralwidget)
        self.find_dir_button.setGeometry(QtCore.QRect(710, 383, 31, 31))
        self.find_dir_button.setObjectName("find_dir_button")
        self.stop_button = QtWidgets.QPushButton(self.centralwidget)
        self.stop_button.setGeometry(QtCore.QRect(690, 500, 93, 28))
        self.stop_button.setObjectName("stop_button")
        self.restart_button = QtWidgets.QPushButton(self.centralwidget)
        self.restart_button.setGeometry(QtCore.QRect(490, 500, 93, 28))
        self.restart_button.setObjectName("restart_button")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 30, 721, 331))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.View4 = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.View4.setObjectName("View4")
        self.gridLayout_3.addWidget(self.View4, 1, 1, 1, 1)
        self.View3 = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.View3.setObjectName("View3")
        self.gridLayout_3.addWidget(self.View3, 1, 0, 1, 1)
        self.View1 = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.View1.setObjectName("View1")
        self.gridLayout_3.addWidget(self.View1, 0, 0, 1, 1)
        self.View2 = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.View2.setObjectName("View2")
        self.gridLayout_3.addWidget(self.View2, 0, 1, 1, 1)
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setGeometry(QtCore.QRect(590, 500, 93, 28))
        self.start_button.setObjectName("start_button")
        self.run_option = QtWidgets.QRadioButton(self.centralwidget)
        self.run_option.setGeometry(QtCore.QRect(489, 420, 100, 20))
        self.run_option.setObjectName("run_option")
        self.logger = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.logger.setGeometry(QtCore.QRect(20, 390, 451, 151))
        self.logger.setObjectName("logger")
        self.directory = QtWidgets.QLabel(self.centralwidget)
        self.directory.setGeometry(QtCore.QRect(510, 390, 181, 16))
        self.directory.setObjectName("directory")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 821, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.find_dir_button.setText(_translate("MainWindow", "..."))
        self.stop_button.setText(_translate("MainWindow", "stop"))
        self.restart_button.setText(_translate("MainWindow", "restart"))
        self.start_button.setText(_translate("MainWindow", "start"))
        self.run_option.setText(_translate("MainWindow", "run"))
        self.directory.setText(_translate("MainWindow", "Directory"))
