# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'v5.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(853, 603)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.find_dir_button = QtWidgets.QToolButton(self.centralwidget)
        self.find_dir_button.setGeometry(QtCore.QRect(720, 450, 31, 31))
        self.find_dir_button.setObjectName("find_dir_button")
        self.stop_button = QtWidgets.QPushButton(self.centralwidget)
        self.stop_button.setGeometry(QtCore.QRect(690, 510, 93, 28))
        self.stop_button.setObjectName("stop_button")
        self.clear_button = QtWidgets.QPushButton(self.centralwidget)
        self.clear_button.setGeometry(QtCore.QRect(490, 510, 93, 28))
        self.clear_button.setObjectName("clear_button")
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setGeometry(QtCore.QRect(590, 510, 93, 28))
        self.start_button.setObjectName("start_button")
        self.directory = QtWidgets.QLabel(self.centralwidget)
        self.directory.setGeometry(QtCore.QRect(500, 460, 181, 21))
        self.directory.setObjectName("directory")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(500, 383, 191, 51))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.run_option = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.run_option.setObjectName("run_option")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.run_option)
        self.gridLayout.addWidget(self.run_option, 0, 0, 1, 1)
        self.ingest_option = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.ingest_option.setObjectName("ingest_option")
        self.buttonGroup.addButton(self.ingest_option)
        self.gridLayout.addWidget(self.ingest_option, 1, 0, 1, 1)
        self.clean_option = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.clean_option.setObjectName("clean_option")
        self.buttonGroup.addButton(self.clean_option)
        self.gridLayout.addWidget(self.clean_option, 0, 1, 1, 1)
        self.bundles_option = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.bundles_option.setObjectName("bundles_option")
        self.gridLayout.addWidget(self.bundles_option, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 853, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.find_dir_button.setText(_translate("MainWindow", "..."))
        self.stop_button.setText(_translate("MainWindow", "stop"))
        self.clear_button.setText(_translate("MainWindow", "clear"))
        self.start_button.setText(_translate("MainWindow", "start"))
        self.directory.setText(_translate("MainWindow", "Compile File :"))
        self.run_option.setText(_translate("MainWindow", "run"))
        self.ingest_option.setText(_translate("MainWindow", "ingest"))
        self.clean_option.setText(_translate("MainWindow", "clean"))
        self.bundles_option.setText(_translate("MainWindow", "bundles"))
