# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Viewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(810, 419)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 40, 721, 331))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.MplWidget1 = MplWidget(self.gridLayoutWidget)
        self.MplWidget1.setObjectName("MplWidget1")
        self.gridLayout_3.addWidget(self.MplWidget1, 0, 0, 1, 1)
        self.MplWidget2 = MplWidget(self.gridLayoutWidget)
        self.MplWidget2.setObjectName("MplWidget2")
        self.gridLayout_3.addWidget(self.MplWidget2, 0, 1, 1, 1)
        self.MplWidget3 = MplWidget(self.gridLayoutWidget)
        self.MplWidget3.setObjectName("MplWidget3")
        self.gridLayout_3.addWidget(self.MplWidget3, 1, 0, 1, 1)
        self.MplWidget4 = MplWidget(self.gridLayoutWidget)
        self.MplWidget4.setObjectName("MplWidget4")
        self.gridLayout_3.addWidget(self.MplWidget4, 1, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
from mplwidget import MplWidget
