# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'v4.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1007, 674)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.find_dir_button = QtWidgets.QToolButton(self.centralwidget)
        self.find_dir_button.setGeometry(QtCore.QRect(870, 443, 31, 31))
        self.find_dir_button.setObjectName("find_dir_button")
        self.stop_button = QtWidgets.QPushButton(self.centralwidget)
        self.stop_button.setGeometry(QtCore.QRect(850, 560, 93, 28))
        self.stop_button.setObjectName("stop_button")
        self.restart_button = QtWidgets.QPushButton(self.centralwidget)
        self.restart_button.setGeometry(QtCore.QRect(650, 560, 93, 28))
        self.restart_button.setObjectName("restart_button")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 30, 901, 371))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.MplWidget4 = MplWidget(self.gridLayoutWidget)
        self.MplWidget4.setObjectName("MplWidget4")
        self.generate4 = QtWidgets.QPushButton(self.MplWidget4)
        self.generate4.setGeometry(QtCore.QRect(0, 0, 93, 28))
        self.generate4.setObjectName("generate4")
        self.gridLayout_3.addWidget(self.MplWidget4, 1, 1, 1, 1)
        self.MplWidget3 = MplWidget(self.gridLayoutWidget)
        self.MplWidget3.setObjectName("MplWidget3")
        self.generate3 = QtWidgets.QPushButton(self.MplWidget3)
        self.generate3.setGeometry(QtCore.QRect(0, 0, 93, 28))
        self.generate3.setObjectName("generate3")
        self.gridLayout_3.addWidget(self.MplWidget3, 1, 0, 1, 1)
        self.MplWidget1 = MplWidget(self.gridLayoutWidget)
        self.MplWidget1.setEnabled(True)
        self.MplWidget1.setObjectName("MplWidget1")
        self.generate1 = QtWidgets.QPushButton(self.MplWidget1)
        self.generate1.setGeometry(QtCore.QRect(0, 0, 93, 28))
        self.generate1.setObjectName("generate1")
        self.gridLayout_3.addWidget(self.MplWidget1, 0, 0, 1, 1)
        self.MplWidget2 = MplWidget(self.gridLayoutWidget)
        self.MplWidget2.setObjectName("MplWidget2")
        self.generate2 = QtWidgets.QPushButton(self.MplWidget2)
        self.generate2.setGeometry(QtCore.QRect(0, 0, 93, 28))
        self.generate2.setObjectName("generate2")
        self.gridLayout_3.addWidget(self.MplWidget2, 0, 1, 1, 1)
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setGeometry(QtCore.QRect(750, 560, 93, 28))
        self.start_button.setObjectName("start_button")
        self.run_option = QtWidgets.QRadioButton(self.centralwidget)
        self.run_option.setGeometry(QtCore.QRect(649, 480, 100, 20))
        self.run_option.setObjectName("run_option")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(50, 420, 511, 181))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.directory = QtWidgets.QLabel(self.centralwidget)
        self.directory.setGeometry(QtCore.QRect(670, 450, 181, 16))
        self.directory.setObjectName("directory")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1007, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.find_dir_button.setText(_translate("MainWindow", "..."))
        self.stop_button.setText(_translate("MainWindow", "stop"))
        self.restart_button.setText(_translate("MainWindow", "restart"))
        self.generate4.setText(_translate("MainWindow", "Generate"))
        self.generate3.setText(_translate("MainWindow", "Generate"))
        self.generate1.setText(_translate("MainWindow", "Generate"))
        self.generate2.setText(_translate("MainWindow", "Generate"))
        self.start_button.setText(_translate("MainWindow", "start"))
        self.run_option.setText(_translate("MainWindow", "run"))
        self.directory.setText(_translate("MainWindow", "Directory"))
from mplwidget import MplWidget
